NT-33: Display number of left cards
EkspoMurinoIndustries/no-thanks pull request #11
Opened 2022-12-21 18:24 UTC by Steellemm

📝 **NT-33**

# Description

Display number of left cards

2022-12-22 09:48 UTC, TorgashSad requested changes
Left to remaining

2022-12-22 09:48 UTC, TorgashSad commented on src/main/kotlin/org/expo/nothanks/model/event/output/RoundStartedMessage.kt
> +    val leftNumberCards: Int
давай remaining, надо
либо remainingCards или numberOfRemainingCards

2022-12-22 09:48 UTC, TorgashSad commented on src/main/kotlin/org/expo/nothanks/model/event/output/TakeCardMessage.kt
> +    val leftNumberCards: Int
тоже

2022-12-22 09:48 UTC, TorgashSad commented on src/main/kotlin/org/expo/nothanks/service/NotificationService.kt
> +            leftNumberCards = lobby.getGame().leftNumberCards()
тоже

2022-12-22 09:48 UTC, TorgashSad commented on src/main/kotlin/org/expo/nothanks/service/NotificationService.kt
> +            leftNumberCards = lobby.getGame().leftNumberCards()
тоже

2022-12-22 09:48 UTC, TorgashSad commented on src/main/kotlin/org/expo/nothanks/utils/GameUtils.kt
> +fun Game.leftNumberCards(): Int {
тоже

2022-12-22 09:48 UTC, TorgashSad commented on src/main/resources/static/js/main.js
> +        updateLeftNumberCards(message['leftNumberCards'])
тоже

2022-12-22 09:48 UTC, TorgashSad commented on src/main/resources/static/js/main.js
> +        updateLeftNumberCards(message['leftNumberCards'])
тоже

2022-12-22 09:48 UTC, TorgashSad commented on src/main/resources/static/js/render.js
> +function updateLeftNumberCards(number) {
тоже

2022-12-22 11:45 UTC, iamsaywhat approved these changes
I have nothing to add to @TorgashSad's comments, so I approve

2022-12-22 11:45 UTC, iamsaywhat commented on src/main/kotlin/org/expo/nothanks/model/event/output/RoundStartedMessage.kt
> +    val leftNumberCards: Int
I vote for `remainingCards`

2022-12-23 07:38 UTC, TorgashSad approved these changes
эх ты

2022-12-23 08:14 UTC, merged