PR for beer
EkspoMurinoIndustries/no-thanks pull request #21
Opened 2024-02-08 17:11 UTC by Steellemm

📝 **Task:** [TaskID](link)

# Description

Short description of the changes and/or problem and what has been done to resolve it.

2024-02-08 17:38 UTC, iamsaywhat approved these changes
GJ

2024-02-09 16:12 UTC, TorgashSad requested changes
шестёрочку поставь, так интереснее внатуре

2024-02-09 16:12 UTC, TorgashSad commented on src/main/resources/application.yml
> +      8: 7
Поставь 6, так по-вкуснее будет
Серьёзно ☝️

2024-02-17 17:08 UTC, Steellemm commented on src/main/resources/application.yml
> +      8: 7
Сделано

2024-02-17 17:09 UTC, TorgashSad approved these changes

2024-02-17 17:11 UTC, merged